DROP TABLE IF EXISTS XCOLA.dbo.E2E_TEST_CASE;

CREATE TABLE XCOLA.dbo.E2E_TEST_CASE(
  TEST_CASE_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
  PROJECT_NAME   VARCHAR(30) NOT NULL REFERENCES E2E_PROJECT
);

INSERT INTO XCOLA.dbo.E2E_TEST_CASE (TEST_CASE_NAME, PROJECT_NAME) VALUES ('PCL-Index-page-test01', 'pcl');
