
DROP TABLE E2E_PROJECT
CREATE TABLE E2E_PROJECT (
  PROJECT_NAME VARCHAR(10) NOT NULL PRIMARY KEY,
  TEST_CLASS_NAMES VARCHAR(50) NOT NULL,
  URL_COLLECTION VARCHAR(200) NOT NULL,
)
GO

DROP TABLE E2E_TEST_CASE
CREATE TABLE E2E_TEST_CASE (
  TEST_CASE_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
  PROJECT_NAME VARCHAR(10) NOT NULL REFERENCES E2E_PROJECT (PROJECT_NAME)
)
GO

DROP TABLE E2E_PAGE_DATA
CREATE TABLE E2E_PAGE_DATA (
  ID NUMERIC IDENTITY(1,1) NOT NULL PRIMARY KEY,
  TEST_CASE_NAME VARCHAR(50) NOT NULL REFERENCES E2E_TEST_CASE (TEST_CASE_NAME),
  PAGE_URL VARCHAR(200) NOT NULL,
  PAGE_SRV_CLASS VARCHAR(20) NOT NULL,
  DATA_JSON_STR VARCHAR(MAX ) NOT NULL
)
GO





